config/routes.rb
Notreditt::Application.routes.draw do
  devise_for :users
  
  root 'posts#index'

  resources :posts do
      resources :comments
  end

  
  
end

# new_user_session GET    /users/sign_in(.:format)                    devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                    devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                   devise/sessions#destroy
#            user_password POST   /users/password(.:format)                   devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)               devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)              devise/passwords#edit
#                          PATCH  /users/password(.:format)                   devise/passwords#update
#                          PUT    /users/password(.:format)                   devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                     devise/registrations#cancel
#        user_registration POST   /users(.:format)                            devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                    devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                       devise/registrations#edit
#                          PATCH  /users(.:format)                            devise/registrations#update
#                          PUT    /users(.:format)                            devise/registrations#update
#                          DELETE /users(.:format)                            devise/registrations#destroy
#            post_comments GET    /posts/:post_id/comments(.:format)          comments#index
#                          POST   /posts/:post_id/comments(.:format)          comments#create
#         new_post_comment GET    /posts/:post_id/comments/new(.:format)      comments#new
#        edit_post_comment GET    /posts/:post_id/comments/:id/edit(.:format) comments#edit
#             post_comment GET    /posts/:post_id/comments/:id(.:format)      comments#show
#                          PATCH  /posts/:post_id/comments/:id(.:format)      comments#update
#                          PUT    /posts/:post_id/comments/:id(.:format)      comments#update
#                          DELETE /posts/:post_id/comments/:id(.:format)      comments#destroy
#                    posts GET    /posts(.:format)                            posts#index
#                          POST   /posts(.:format)                            posts#create
#                 new_post GET    /posts/new(.:format)                        posts#new
#                edit_post GET    /posts/:id/edit(.:format)                   posts#edit
#                     post GET    /posts/:id(.:format)                        posts#show
#                          PATCH  /posts/:id(.:format)                        posts#update
#                          PUT    /posts/:id(.:format)                        posts#update
#                          DELETE /posts/:id(.:format)                        posts#destroy
#                     root GET    /                                           posts#index

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	accepts_nested_attributes_for :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :load_post
  def index
    @comments = @post.comments.all
		@user = current_user
  end

  def new
    @comment = @post.comments.new
  end

  def create
    @comment = @post.comments.new(comment_params)
    if @comment.save
      redirect_to post_comments_path(@post)
    end
  end

  # def show
  #   @comment = @post.comments.find(params[:id])
  # end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_comments_path(@post)
  end

  private
  def comment_params
    params[:comment].permit(:title)
  end

  def load_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
    @posts = Post.all
    @user = current_user
  end

  def new
    @post = Post.new
  end

  def create
    # binding.pry
    @post = Post.create(post_params)
    redirect_to posts_path
  end

  private
  def post_params
    params[:post].permit(:title, :body, :comments_attributes=>[:title])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/index.html.erb
<h1>Comments on "<%=@post.title%>"</h1>

<% @comments.each do |comment| %>
  "<%= comment.title %>" <%= link_to "delete", [@post, comment], method: :delete, data: {confirm: "Are you sure?"} %> <br>

  <p class="commentby">-- <%= @user.email %></p>

<% end %>
<br>
<div class="buttons">
  <%= link_to "Add a Comment", new_post_comment_path, :class => "btn btn-info" %><br>
  <br>
  <%= link_to "Back to all Posts", posts_path, :class => "btn btn-info" %>
</div>

app/views/comments/new.html.erb
<h1>Add your comment to "<%=@post.title%>"</h1>

<%= form_for([@post, @comment]) do |f| %>
  <%= f.text_area :title, placeholder: "Leave a dumb comment" %>
  <%= f.submit %>
<% end %>

app/views/comments/show.html.erb
Comment Deetz

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notreditt</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>NOTREDITT</h1>
<p>Take a Look at this crap:</p>

<% @posts.each do |post| %>
  <li><%= link_to post.title, post_comments_path(post)%></li>
<% end %>

<%= link_to "Create New Dumb Reddit", new_post_path %>

app/views/posts/new.html.erb
<h1>Create A New NotReditt</h1>

<%= form_for @post do |f| %>
  <%= f.text_field :title, placeholder: "Name Of NotReddit" %>
  <%= f.text_area :body, placeholder: "Say something to the Internets" %>

  <%= f.submit %>
  <% end %>